'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MeaInspWorksheet

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.WebMasterV4.MenuTCRC1

    '''<summary>
    '''MeaInspBeforeAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeaInspBeforeAdd As Global.WebMasterV4.MeaInspBeforeAdd

    '''<summary>
    '''tWONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tWONo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bSearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bAddInsp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bAddInsp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bCount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvInsp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvInsp As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''tWONoAft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tWONoAft As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bSearchAft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bSearchAft As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bCountAft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bCountAft As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''gvInspAft control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvInspAft As Global.System.Web.UI.WebControls.GridView
End Class
