'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MeaInspTemplateSec

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.WebMasterV4.MenuTCRC1

    '''<summary>
    '''MeaTemplateSecEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeaTemplateSecEdit As Global.WebMasterV4.MeaTemplateSecEdit

    '''<summary>
    '''MeaTemplateSecUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeaTemplateSecUpload As Global.WebMasterV4.MeaTemplateSecUpload

    '''<summary>
    '''tID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tUnitDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tUnitDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tComp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tRegBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tRegBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tRegDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tRegDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bAdd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bUpload As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bShowSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bShowSample As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bBack As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gvSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSection As Global.System.Web.UI.WebControls.GridView
End Class
