'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MeaTemplateSecDetailsEdit

    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''IDDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IDDetail As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''Action control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Action As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TypeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TypeID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tIDGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tIDGroup As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dIDDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dIDDetails As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tIDDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tIDDetail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lIDDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lIDDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tSeq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tSeq As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tSec As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tcurSubSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tcurSubSec As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''tSubSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tSubSec As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tItem As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lItem As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dRowCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tRowCount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lRowCount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lRowCount As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dValType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dValType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddValType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddValType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lddValType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lddValType As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''dCostCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dCostCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tCostCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tCostCol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lCostCol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCostCol As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
