'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MeaTemplateSecDetails

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.WebMasterV4.MenuTCRC1

    '''<summary>
    '''MeaTemplateSecDetailsEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeaTemplateSecDetailsEdit As Global.WebMasterV4.MeaTemplateSecDetailsEdit

    '''<summary>
    '''MeaInspTemplateRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeaInspTemplateRef As Global.WebMasterV4.MeaInspTemplateRef

    '''<summary>
    '''MeaTemplatePicUpload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeaTemplatePicUpload As Global.WebMasterV4.MeaTemplatePicUpload

    '''<summary>
    '''tID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tUnitDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tUnitDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tComp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tRegBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tRegBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tRegDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tRegDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bAdd As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bAddRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bAddRef As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bUploadPict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bUploadPict As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bBack As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''TitleSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TitleSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSection As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''rpt_SubSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpt_SubSection As Global.System.Web.UI.WebControls.Repeater
End Class
